#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: set sw=4 ts=4 sts=4 et tw=80 fdm=indent :
#
# Copyright (c) 2008 Ali Polatel <polatel@gmail.com>
#
# This file is part of the paludis-utils. paludis-utils is free software; you
# can redistribute it and/or modify it under the terms of the GNU General
# Public License version 2, as published by the Free Software Foundation.
#
# paludis-utils is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

"""paludis-utils -- Useful utilities for paludis
"""

from __future__ import generators

import os
import sys
import getopt

# Signal handling
import signal
from putils.common import exiting_signal_handler

def get_applet(name):
    """Get applet by name."""
    try:
        applet = __import__("putils.applets", globals(), locals(), [name])
        applet = getattr(applet, name)
    except (AttributeError, ImportError):
        return None

    return applet

def arrange_separator(string, sep=":"):
    """Arrange separators so they appear below each other."""
    lines = string.splitlines()

    max_index = 0
    for line in lines:
        if line.index(sep) > max_index:
            max_index = line.index(sep)

    for line in lines:
        if line.index(sep) != max_index:
            yield line.replace(sep, " " * (max_index - line.index(sep)) + sep)
        else:
            yield line

def usage():
    """Print usage"""
    print "Usage: p <applet> <args>"
    print "Invoke a paludis-utils applet"
    print
    print "Currently defined applets:"

    import putils.applets

    applet_usage = "p <applet> <args> : Virtual applet\n"
    for applet_name in putils.applets.__all__:
        applet = get_applet(applet_name)
        if applet is None:
            raise NameError("No such applet: '" + applet_name + "'")
        applet_usage += applet.usage.replace("%prog", applet_name).replace("\n", " : ")
        applet_usage += "\n"

    print "\n".join(arrange_separator(applet_usage))

def main():
    signal.signal(signal.SIGINT, exiting_signal_handler)

    if not os.path.islink(sys.argv[0]):
        # Virtual applet, p
        options, args = getopt.getopt(sys.argv[1:], "hV", ["help", "version"])
        for o, a in options:
            if o in ("-h", "--help"):
                usage()
                sys.exit(0)
            elif o in ("-V", "--version"):
                from putils.getopt import version
                print version()
                sys.exit(0)

        if not args:
            usage()
            sys.exit(0)
        else:
            applet_name = args[0]
            sys.argv = sys.argv[sys.argv.index(applet_name):]
    else:
        applet_name = os.path.basename(sys.argv[0])

    applet = get_applet(applet_name)
    if applet is None:
        print >>sys.stderr, "Usage error: No such applet", applet_name
        print >>sys.stderr, "Try p --help"
        sys.exit(1)

    return applet.main()

if __name__ == '__main__':
    main()
